### ISSUE TITLE
Getting `(void-variable corfu--frame)`

### ISSUE THREAD

**Issue by marlonschlosshauer** [casouri/eldoc-box#125]
Installed the latest version and I'm getting the following in the echo area every time I hover over a symbol with `eldoc-box-hover-at-point-mode` enabled:

```
eldoc error: (void-variable corfu--frame)
```

I don't use corfu (using built-in `completion-at-point`). However, installing corfu (and loading) fixed it. Probably an unintended error from #123?

**Comment by casouri** [comment]
oops, yes, I fixed it now.

**Comment by marlonschlosshauer** [comment]
Just updated and the error is gone. Thank you!

**Comment by marlonschlosshauer** [comment]
Nevermind, if I use `eldoc-box-hover-at-point-mode` I still get the error (and the box gets put at the bottom right).

**Comment by casouri** [comment]
Hmmm, my elisp-fu might be betraying me. Now I added a `boundp` check, surely this will fix the error.

**Comment by marlonschlosshauer** [comment]
And surely it did, thanks for the quick fix!
