### ISSUE TITLE
Child frame border

### ISSUE THREAD

**Issue by seagle0128** [casouri/eldoc-box#13]
- GNU Emacs 26.1
- macOS Mojave
- Centuar Emacs https://github.com/seagle0128/.emacs.d

I see this face`eldoc-box-border`in `eldoc-box`, but it seems not working in my env.
I am not sure if it's a bug or configuration issue. Please help to take a look. Thanks in advance!

![image](https://user-images.githubusercontent.com/140797/53752364-02613700-3ee1-11e9-9951-d99cc2466b31.png)

**Comment by casouri** [comment]
It is a bug. For some reason, it works on Linux but not Mac. For a workaround, I just set a different background color for the doc (as you can see in the screenshot in README), which actually looks better than a border.

**Comment by seagle0128** [comment]
Thank you for the reply!

**Comment by seagle0128** [comment]
One more question, I noticed the left fringe (but no right fringe) is kept and it's different face. Is it as designed?

**Comment by casouri** [comment]
Could you double check if 6caf8a271059b32bbe850ed0e056d0b235233d63 fixes the problem?

**Comment by seagle0128** [comment]
@casouri  I don't think the issue was addressed.

The face of `fringe` should inherit  the face of `eldoc-box-body` while not `default`.

**Comment by casouri** [comment]
`eldoc-box-body` is a dummy face, it just provides the `:background` and `:font` attribute. I alter `default` face of the childframe according to `eldoc-box-body`. So they are the equivalent. (I mean I can make `default` inherit `eldoc-box-body` but then I have to set `:background` and `:font` of `default` to `nil`, which doesn't really make any difference.

**Comment by seagle0128** [comment]
But users may customize the face of `eldoc-box-body` themselves. How to handle this case?

BTW: I still observe the issue with the latest version.

**Comment by casouri** [comment]
> How to handle this case?

If you mean the other attributes, I can add them if anyone needs them. If you mean syncing the face, the face attributes are reset constantly, so there shouldn't be much problem.

> BTW: I still observe the issue with the latest version.

Have you tried with vanilla Emacs? Because I tested on vanilla Emacs and my config (emacs 27).

**Comment by seagle0128** [comment]
I tested with vanilla Emacs 26.1 (`emacs -Q`) on macOS, using built-in `tango-dark` theme. The screenshot is below.

![image](https://user-images.githubusercontent.com/140797/53834621-1890f500-3fbe-11e9-821b-01e989893eb5.png)

**Comment by casouri** [comment]
I pushed another commit, could you please verify?

**Comment by seagle0128** [comment]
The issue doesn't exist in `vanilla Emacs`, but still exists in `Centaur Emacs`. Have no idea...
