### ISSUE TITLE
Hard requirement on eglot?

### ISSUE THREAD

**Issue by joostkremers** [casouri/eldoc-box#46]
Would it be possible to pass `t` for `NOERROR` to `(require 'eglot)`? Right now, an error pops up every time I start Emacs complaining about `eglot` not being found.

Since I don't use eglot, I don't really mind if the eglot macro calls aren't compiled.

**Comment by joostkremers** [comment]
Actually, it's worse than just an annoying warning popping up when I start Emacs. `eldoc-box` no longer works for me, I keep getting errors about eglot not being found when trying to use `eldoc-box`.

**Comment by casouri** [comment]
Oh I don't know commit message auto close issues. Anyway this should be fixed now. Thanks!

**Comment by casouri** [comment]
If it didn't fix for you please re-open the issue and I'll see what went wrong.

**Comment by joostkremers** [comment]
Hi, thanks for the quick reply. I don't get a warning at startup anymore and eldoc-box works again, but I do still get some warnings:

```
Warning (comp): eldoc-box.el:481:8: Warning: ‘(Hover)’ is a malformed function
Warning (comp): eldoc-box.el:485:41: Warning: reference to free variable ‘contents’
Warning (comp): eldoc-box.el:485:50: Warning: reference to free variable ‘range’
Warning (comp): eldoc-box.el:494:35: Warning: the function ‘eldoc-box--eglot-help-at-point-cleanup’ is not known to be defined.
```

These are warnings from native compilation and are probably due to the fact that the relevant macros aren't defined, so I'm not sure they're something to worry about.

> If it didn't fix for you please re-open the issue and I'll see what went wrong.

I can't reopen the issue, apparently, but perhaps it's not necessary. If the warnings above only pop up during native compilation, they only happen when the package gets updated. I don't know if it'd be possible to do anything about that.

> Oh I don't know commit message auto close issues. 

Yeah, Github does that if you write something like "Fixes #XXX" with "#XXX" an issue number. :slightly_smiling_face:

**Comment by casouri** [comment]
_I_ can reopen it, aha! I wonder what's going on during native comp that causes this. I'll have a look at it when I got time, since at least it is not critical anymore ;-)

**Comment by dalugm** [comment]
I noticed this line will lead Emacs require eglot when start up

https://github.com/casouri/eldoc-box/blob/939724afef1ec18386b7e45e697a92b85c6d66de/eldoc-box.el#L628

I used a hook which will enable eldoc-box after enable eldoc, and eldoc
is enabled by default.

Sometimes I just want to check docstring in eldoc-box showed by eldoc
and it doesn't need eglot. But this line leads to enable eglot when
enable eldoc-box, which slows down my Emacs initialization.

Maybe it's better to wrap it with a `with-eval-after-load`?

```emacs-lisp
(with-eval-after-load 'eglot
  ...)
```

**Comment by casouri** [comment]
That was added so that byte-compiling doesn't break, since some people like to byte-compile their packages upfront.

But we don't really need that code anymore, since we have `eldoc-box-help-at-point`. I obsoleted `eldoc-box-eglot-help-at-point` and removed the code requiring eglot.
